version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Expose Prometheus on localhost:9090
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/config/minio-alerts.yml:/etc/prometheus/minio-alerts.yml:ro
    restart: unless-stopped  # Automatically restart Prometheus
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO Console
      - "9001:9001"  # MinIO Management Console
    environment:
      MINIO_ROOT_USER: "admin"       # MinIO root user
      MINIO_ROOT_PASSWORD: "password" # MinIO root password
      MINIO_PROMETHEUS_AUTH_TYPE: "public"  # Expose metrics without a bearer token
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data           # Storage for MinIO
    restart: unless-stopped
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
