global:
  scrape_interval: 5s    # Adjust scrape interval as needed
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']  # Scrape metrics from the Pushgateway


  - job_name: 'minio-job'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['minio:9000']      # Directly scrape metrics from MinIO
